name: Backend CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: learnup_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: pdo, pdo_mysql
          coverage: none

      - name: Install Dependencies
        working-directory: backend-api
        run: |
          composer install --no-dev --prefer-dist
          cp .env.example .env
          php artisan key:generate

      - name: Run Migrations
        working-directory: backend-api
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: learnup_db
          DB_USERNAME: user
          DB_PASSWORD: password
        run: php artisan migrate --force

      - name: Run Tests
        working-directory: backend-api
        run: php artisan test
