name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: learnup_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=root" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: pdo, pdo_mysql
          coverage: none

      - name: Install Dependencies
        run: |
          composer install --no-dev --prefer-dist
          cp .env.example .env
          php artisan key:generate

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: learnup_db
          DB_USERNAME: user
          DB_PASSWORD: password
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/learnup_backend
            git pull origin main
            composer install --no-dev --prefer-dist
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan queue:restart
            systemctl restart php8.1-fpm
