name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Directory Structure (Debugging)
        run: ls -R  # Helps confirm the folder structure

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: |
          cd LearnUp
          npm install

      - name: Run Linting
        run: |
          cd LearnUp
          npm run lint || echo "No lint script found, skipping..."

      - name: Build React App
        run: |
          cd LearnUp
          npm run build
